import { Injectable } from '@angular/core';
import { City, DogSize, Spot } from '../models/spot.model';

const SPOTS: Spot[] = [
  // ── 대전 ────────────────────────────────────────────────────────────────
  {
    id: '1',
    name: '한밭수목원',
    address: '대전 서구 둔산대로 169',
    lat: 36.3665, lng: 127.3884,
    city: 'daejeon',
    spot_type: 'park',
    size_suitable: ['small', 'medium', 'large'],
    features: ['parking', 'toilet', 'bench', 'trail', 'shade', 'water'],
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Hanbat_Aboretum_Garden_under_the_Moon.jpg',
    description: '대전 도심 속 넓은 수목원. 동·서원 합계 38만㎡의 잘 정비된 산책로와 넓은 잔디밭이 있어 모든 크기의 강아지와 여유롭게 산책할 수 있습니다.',
    why_recommended: '대전 최대 규모 수목원으로 포장 산책로가 넓고 평탄해 소형견 유모차도 이동 가능합니다. 그늘과 벤치가 풍부해 더운 날에도 쾌적하며, 목줄 착용 시 모든 견종 입장할 수 있습니다.',
    tips: [
      '동원·서원 개방 시간 확인 필수 (오전 5시 ~ 오후 10시)',
      '동원 연못 주변에 그늘·벤치 집중, 여름 피서지로 최적',
      '서원 입구 무료 주차장 이용 권장 (주말 오전 일찍)',
      '강아지 배변봉투 비치함 곳곳에 있어 매너 산책 가능',
    ],
    amenity_detail: {
      parking: '서원·동원 입구 모두 무료 주차장 운영 (주말 오전 이른 시간 추천)',
      toilet:  '원 내 여러 곳, 전반적으로 청결도 양호',
      water:   '음수대 수십 곳 — 반려견도 이용 가능한 낮은 수도꼭지 있음',
      bench:   '전 구간에 수십 개 벤치·파고라 쉼터',
      shade:   '수목원 특성상 교목 그늘이 산책로 전체를 덮음',
      trail:   '포장 산책로 약 3 km, 경사 거의 없음',
    },
  },
  {
    id: '2',
    name: '갑천 자연생태공원',
    address: '대전 서구 갑천로 217',
    lat: 36.3532, lng: 127.3423,
    city: 'daejeon',
    spot_type: 'riverside',
    size_suitable: ['medium', 'large'],
    features: ['trail', 'bench', 'water', 'shade', 'parking'],
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Hiking_path_along_Gapcheon_in_Daejeon.jpg',
    description: '갑천변을 따라 이어지는 긴 직선 산책로. 탁 트인 강변 공간이 넓어 중·대형견이 마음껏 뛰기에 최적입니다. 소형견은 자전거 통행에 주의가 필요합니다.',
    why_recommended: '갑천 양안을 따라 총 12 km의 수변 산책로가 펼쳐집니다. 자전거 도로와 분리된 구간이 많아 중·대형견이 마음껏 달릴 수 있고, 탁 트인 강바람이 여름에도 시원합니다.',
    tips: [
      '자전거 통행이 많으니 소형견은 목줄을 짧게 유지',
      '평일 이른 아침(6~8시) 방문 시 가장 한적',
      '강변 풀숲 구간은 진드기 주의 (봄~가을)',
      '갑천수변공원 유료 주차장 이용, 주말 혼잡',
    ],
    amenity_detail: {
      parking: '갑천수변공원 주차장 유료 (주말 혼잡, 이른 아침 추천)',
      trail:   '갑천 양안 합계 약 12 km 수변 산책로',
      bench:   '구간별 쉼터·벤치 설치',
      water:   '음수대 간헐적으로 배치 (간격 약 2 km)',
      shade:   '개방형이라 햇볕 강한 편 — 모자·선크림 필수',
    },
  },
  {
    id: '3',
    name: '엑스포 과학공원',
    address: '대전 유성구 대덕대로 480',
    lat: 36.3740, lng: 127.3814,
    city: 'daejeon',
    spot_type: 'park',
    size_suitable: ['small', 'medium', 'large'],
    features: ['parking', 'toilet', 'bench', 'trail', 'water', 'shade'],
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/5/54/Daejeon_Expo_Science_Park.jpg',
    description: '93 대전엑스포 터에 조성된 대형 공원. 잔디광장과 호수 산책로가 잘 갖춰져 있으며 크기 제한 없이 산책하기 좋습니다.',
    why_recommended: '호수 둘레 약 1.5 km 포장 산책로와 넓은 잔디광장이 있어 모든 견종에 적합합니다. 갑천 산책로와도 연결되어 코스를 이어 걸을 수 있어 운동량이 필요한 대형견에게 특히 추천합니다.',
    tips: [
      '특별 전시·행사 기간 방문객 급증, 사전 확인 권장',
      '엑스포 다리 건너 갑천 수변 연계 산책 가능',
      '주차장 입구 쪽 잔디광장이 강아지 놀이에 최적',
      '음수대 위치 미리 확인 — 호수 동편에 집중',
    ],
    amenity_detail: {
      parking: '메인 주차장 유료 (2시간 2,000원, 주말 주차 대기 있음)',
      toilet:  '공원 내 여러 곳 분산 배치',
      bench:   '호수 주변 벤치 및 파고라 다수',
      trail:   '호수 둘레 약 1.5 km 포장 산책로',
      water:   '음수대 호수 동편에 여러 곳',
      shade:   '호수 주변 교목 그늘 구간 있음',
    },
  },
  {
    id: '4',
    name: '보문산 시민공원',
    address: '대전 중구 보문산공원로 170',
    lat: 36.2967, lng: 127.4076,
    city: 'daejeon',
    spot_type: 'forest',
    size_suitable: ['small', 'medium'],
    features: ['trail', 'shade', 'bench', 'toilet', 'parking'],
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Daejeon_Metropolitan_City_in_Korea%2C_view_from_Bomunsan_Fortress.jpg',
    description: '대전 시내를 내려다볼 수 있는 숲길 산책로. 경사 구간이 있어 소형·중형견에게 적합하며, 대형견은 체력 부담이 있을 수 있습니다.',
    why_recommended: '도심에서 접근하기 쉬운 숲 산책지로 흙길·돌길이 혼재해 발바닥 자극에 좋습니다. 하단부 평탄 구간(왕복 약 1 km)은 소형견도 부담 없이 즐길 수 있으며, 울창한 숲 그늘 덕분에 여름에도 시원합니다.',
    tips: [
      '하단부 평탄 구간(왕복 1 km)은 소형견도 OK',
      '정상 방향 급경사 구간은 대형견도 체력 소모 큼',
      '여름 성수기 오전 7시 전 방문 권장',
      '주말 오전 10시 이후 입구 주차장 포화 상태',
    ],
    amenity_detail: {
      parking: '시민공원 입구 유료 주차장 (규모 협소, 주말 일찍 도착 필수)',
      toilet:  '입구 및 중간 쉼터 2곳',
      trail:   '흙길·돌길 혼재, 하단부 완만 / 상단부 급경사',
      shade:   '울창한 숲으로 산책로 전체 그늘',
      bench:   '중간 쉼터 여러 곳에 벤치 배치',
    },
  },
  {
    id: '5',
    name: '계족산 황톳길',
    address: '대전 대덕구 장동 산 12',
    lat: 36.3952, lng: 127.4782,
    city: 'daejeon',
    spot_type: 'trail',
    size_suitable: ['medium', 'large'],
    features: ['trail', 'shade', 'parking', 'toilet', 'bench'],
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/7/76/Daejeon_southern_cityscape_from_Gyejoksan.jpg',
    description: '총 14.5 km의 황톳길 트레일. 체력이 좋은 중·대형견에게 최적의 장거리 코스입니다. 소형견은 체력 소모가 크므로 짧은 코스(2~3 km)만 권장합니다.',
    why_recommended: '전국 최장 14.5 km 황톳길 트레일로, 촉촉한 황토 흙길이 강아지 발바닥에 부드럽습니다. 오르내림이 완만해 체력이 좋은 중·대형견의 장거리 산책에 최적이며, 사계절 내내 울창한 숲 그늘이 이어집니다.',
    tips: [
      '화장실은 들머리와 중간 2~3곳뿐 — 미리 확인 필수',
      '맨발 걷기 행사 기간(봄·가을 주말) 방문객 폭증',
      '비 온 뒤 이틀은 황토 진창 주의, 발바닥 세척 필수',
      '간식·물 충분히 준비 — 중간 편의점 없음',
    ],
    amenity_detail: {
      parking: '장동 들머리 무료 주차장 (주말 오전 일찍 만차)',
      toilet:  '들머리 및 중간 2~3곳',
      trail:   '황톳길 14.5 km 전 구간, 경사 완만',
      shade:   '숲길 전 구간 그늘 충분',
      bench:   '중간 쉼터 여러 곳에 벤치',
    },
  },
  {
    id: '6',
    name: '월평공원',
    address: '대전 서구 월평동 산 1-1',
    lat: 36.3499, lng: 127.3631,
    city: 'daejeon',
    spot_type: 'forest',
    size_suitable: ['small', 'medium'],
    features: ['trail', 'shade', 'bench', 'parking'],
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/5/51/Wolpyeong_Park.JPG',
    description: '서구 도심 속 도시숲. 잘 정비된 평탄한 둘레길이 있어 소형·중형견의 일상 산책 코스로 안성맞춤입니다.',
    why_recommended: '대전 서구 도심에서 도보 접근 가능한 도시숲입니다. 약 2 km의 평탄한 흙길 둘레길이 정비되어 있어 이른 아침 조용한 숲 산책을 즐기기에 제격이며, 소형·중형견 일상 산책로로 꾸준히 인기입니다.',
    tips: [
      '평일 이른 아침(6~8시) 방문 시 가장 한적',
      '비 온 다음날은 흙길이 미끄럽고 진흙 많음',
      '주차 공간 한정적 — 인근 주택가 도보 접근 권장',
      '목줄 필수 — 좁은 숲길에 등산객도 이용',
    ],
    amenity_detail: {
      parking: '인근 거리 주차 가능하나 공간 한정 (도보 접근 권장)',
      trail:   '흙길 둘레길 약 2 km, 대부분 평탄',
      shade:   '울창한 도시숲으로 전 구간 그늘',
      bench:   '중간 쉼터 벤치 여러 곳',
    },
  },
  {
    id: '7',
    name: '유성 근린공원',
    address: '대전 유성구 봉명동 278',
    lat: 36.3624, lng: 127.3363,
    city: 'daejeon',
    spot_type: 'park',
    size_suitable: ['small'],
    features: ['bench', 'shade', 'water', 'toilet'],
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/f/fd/%EC%9C%A0%EB%A6%BC%EA%B3%B5%EC%9B%90_%EB%B0%98%EB%8F%84%EC%A7%80.jpg',
    description: '유성온천 인근의 아담한 근린공원. 조용하고 한적해 소형견과 느긋하게 산책하기 좋습니다. 벤치와 그늘이 풍부해 쉬어가기도 편합니다.',
    why_recommended: '유성온천 관광지 인근에 있어 접근성이 좋고, 평일에는 방문객이 거의 없어 소형견과 조용히 산책하기에 완벽합니다. 정비된 잔디밭과 교목 그늘이 풍부해 강아지가 잠시 쉬어가기도 좋습니다.',
    tips: [
      '주말·연휴에는 온천 관광객으로 주변이 혼잡할 수 있음',
      '목줄 필수 착용 공원 — 잔디밭 이탈 주의',
      '오전 8시 이전 방문 시 가장 조용',
      '주차는 인근 유료 주차장 이용 (도보 5분)',
    ],
    amenity_detail: {
      bench:  '잔디밭 주변 벤치 다수, 그늘 아래 위치',
      shade:  '교목 그늘 풍부',
      water:  '음수대 1곳 (공원 중앙)',
      toilet: '공원 내 화장실 1개소',
    },
  },
  {
    id: '8',
    name: '도안 근린공원',
    address: '대전 서구 도안동 1374',
    lat: 36.3243, lng: 127.3362,
    city: 'daejeon',
    spot_type: 'park',
    size_suitable: ['small', 'medium', 'large'],
    features: ['parking', 'bench', 'water', 'trail', 'offleash'],
    image_url: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=600&q=80',
    description: '도안 신도시에 조성된 넓은 잔디광장 공원. 펜스 구역이 있어 대형견이 목줄을 풀고 뛰어놀 수 있습니다. 주차도 넉넉합니다.',
    why_recommended: '대전 신도시 도안에 조성된 넓은 공원으로, 목줄 해제 가능한 펜스 구역이 운영됩니다. 대전 시내에서 애견 목줄 해제 구역을 갖춘 몇 안 되는 공원 중 하나로 대형견 보호자에게 특히 추천합니다.',
    tips: [
      '목줄 해제 구역 운영 시간 사전 확인 (계절별 변경)',
      '주말 오전 10~12시 대형견 가족 방문 집중',
      '신도시 공원이라 시설 청결도·유지관리 우수',
      '펜스 구역 입장 전 개체 간 교감 여부 확인 필수',
    ],
    amenity_detail: {
      parking: '공원 인근 무료 주차 가능, 주말에도 여유 있음',
      bench:   '잔디광장 주변 벤치 다수',
      water:   '음수대 2곳 (펜스 구역 내·외 각 1곳)',
      trail:   '포장 산책로 공원 전체 순환',
      offleash: '펜스형 목줄 해제 구역 공식 운영 (운영 시간 확인 필수)',
    },
  },
  {
    id: '9',
    name: '대청호 수변공원',
    address: '대전 대덕구 미호동 일원',
    lat: 36.4634, lng: 127.5130,
    city: 'daejeon',
    spot_type: 'riverside',
    size_suitable: ['small', 'medium', 'large'],
    features: ['parking', 'bench', 'trail', 'shade', 'toilet'],
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Daecheong_Dam_Water_Culture_Center_-_%EB%8C%80%EC%B2%AD%EB%8C%90%EB%AC%BC%EB%AC%B8%ED%99%94%EA%B4%80.jpg',
    description: '대청댐 인근 광활한 호수 수변공원. 드넓은 자연 속에서 대형견이 자유롭게 산책할 수 있으며, 소형견과 함께하는 드라이브 겸 나들이 코스로도 인기입니다.',
    why_recommended: '대전 도심에서 차로 20~30분 거리의 대청호 수변에 펼쳐진 광활한 자연 공원입니다. 드넓은 공간과 맑은 공기 속에서 모든 크기의 강아지가 자유롭게 산책할 수 있으며, 봄 벚꽃·가을 단풍 시즌에는 절경이 펼쳐집니다.',
    tips: [
      '왕복 2~3시간 코스 — 간식·물 충분히 준비 필수',
      '봄 벚꽃 시즌 방문객 폭증, 이른 아침(7시 전) 추천',
      '낚시 구역과 산책 구역 구분 — 낚싯줄 주의',
      '대형견도 목줄 필수, 야생동물 출몰 구간 있음',
    ],
    amenity_detail: {
      parking: '수변공원 주차장 무료 (주말 성수기 혼잡)',
      toilet:  '주차장 인근 화장실 1개소',
      bench:   '수변 벤치 여러 곳',
      trail:   '수변 산책로 약 5 km (일부 비포장)',
      shade:   '교목 그늘 구간과 개방 구간 혼재',
    },
  },
  {
    id: '10',
    name: '천연기념물센터 생태공원',
    address: '대전 유성구 대덕대로 481번길 92',
    lat: 36.3682, lng: 127.3005,
    city: 'daejeon',
    spot_type: 'forest',
    size_suitable: ['small', 'medium'],
    features: ['trail', 'shade', 'bench', 'parking'],
    image_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=80',
    description: '평일에는 거의 방문객이 없는 조용한 생태공원. 자연 그대로의 숲길이 소형견과 느린 산책을 즐기기에 완벽합니다.',
    why_recommended: '방문객이 매우 적어 사실상 강아지와 단둘이 산책할 수 있는 조용한 생태 숲길입니다. 주차가 넉넉하고 무료이며, 자연 오솔길이 소형·중형견과 여유로운 숲 산책을 즐기기에 최적입니다.',
    tips: [
      '주말에도 방문객이 거의 없어 독립적인 산책 가능',
      '자연 숲길이라 진드기 예방 처리 후 방문 권장',
      '주차 공간 넉넉하고 무료 — 접근성 우수',
      '천연기념물 전시관도 함께 관람 가능 (강아지는 외부)',
    ],
    amenity_detail: {
      parking: '전용 주차장 무료, 규모 넉넉함',
      trail:   '자연 오솔길·흙길 (정비된 구간과 비정비 구간 혼재)',
      shade:   '울창한 숲으로 전 구간 그늘 충분',
      bench:   '산책로 곳곳에 쉼터 벤치',
    },
  },

  // ── 세종 ────────────────────────────────────────────────────────────────
  {
    id: '11',
    name: '세종 중앙공원',
    address: '세종특별자치시 한솔동 979',
    lat: 36.5184, lng: 127.2586,
    city: 'sejong',
    spot_type: 'park',
    size_suitable: ['small', 'medium', 'large'],
    features: ['parking', 'toilet', 'bench', 'trail', 'water', 'shade', 'offleash'],
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/0/0b/%EA%B5%AD%EB%A6%BD%EC%84%B8%EC%A2%85%EC%88%98%EB%AA%A9%EC%9B%901.jpg',
    description: '세종시 도심 한가운데 자리한 56만㎡ 규모의 대형 공원. 잘 정비된 산책로와 잔디광장, 반려동물 전용 놀이공간(애견런)이 마련돼 있어 모든 크기의 강아지가 뛰어놀기에 최적입니다.',
    why_recommended: '세종시 최대 공원으로 공식 애견런(목줄 해제 구역)이 운영됩니다. 음수대마다 반려동물 전용 물그릇이 비치되어 있고, 반려견 동반 카페가 공원 내외에 있어 수도권 수준의 반려동물 인프라를 갖추고 있습니다.',
    tips: [
      '애견런 이용 시 광견병 접종 증명서 지참 필수',
      '주말 오전 9~11시 애견런 이용객 집중',
      '공원 내 카페 다수, 반려견 동반 가능 여부 현장 확인',
      '국립세종수목원과 인접 — 연계 방문 추천',
    ],
    amenity_detail: {
      parking:  '공원 주변 공영 주차장 여러 곳 (유료, 주말 대기 있음)',
      toilet:   '공원 내 여러 곳, 청결도 우수',
      water:    '음수대 다수 — 반려동물 전용 낮은 물그릇 비치',
      bench:    '잔디광장·산책로 주변 벤치 수십 개',
      offleash: '애견런(펜스 목줄 해제 구역) 공식 운영 (접종 증명서 필요)',
      shade:    '교목 그늘과 파고라 구간 다수',
      trail:    '포장 산책로 약 5 km 순환',
    },
  },
  {
    id: '12',
    name: '금강 수변공원',
    address: '세종특별자치시 연기면 강외면 일원',
    lat: 36.5020, lng: 127.2550,
    city: 'sejong',
    spot_type: 'riverside',
    size_suitable: ['medium', 'large'],
    features: ['trail', 'bench', 'water', 'shade', 'parking'],
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/1/16/Geumnambo_in_Sejong_City.jpg',
    description: '금강변을 따라 이어지는 넓은 수변 산책로. 강바람을 맞으며 산책하기 좋고 탁 트인 공간 덕분에 중·대형견이 여유롭게 뛸 수 있습니다.',
    why_recommended: '금강을 따라 약 10 km의 수변 산책로가 이어집니다. 세종 보행교 일대는 자전거 도로와 분리된 전용 산책 구간으로, 강바람을 맞으며 달리는 것을 좋아하는 중·대형견에게 특히 추천합니다.',
    tips: [
      '강변이라 여름 낮 직사광선 강함 — 이른 아침 방문 권장',
      '홍수기(7~8월) 수위 상승 시 일부 구간 접근 제한',
      '강가 풀숲 진드기 주의 (봄~가을)',
      '세종 보행교 일대가 산책 환경 가장 좋음',
    ],
    amenity_detail: {
      parking: '수변공원 인근 공영 주차장 이용 가능',
      trail:   '금강 수변 산책로 약 10 km',
      bench:   '구간별 쉼터·벤치 설치',
      water:   '음수대 간헐적 배치 (간격 약 3 km)',
      shade:   '개방형 수변이라 그늘 적음 — 이른 아침 필수',
    },
  },
  {
    id: '13',
    name: '밀마루 전망대 생태공원',
    address: '세종특별자치시 연서면 쌍류리 일원',
    lat: 36.5296, lng: 127.2208,
    city: 'sejong',
    spot_type: 'trail',
    size_suitable: ['small', 'medium'],
    features: ['trail', 'shade', 'bench', 'parking'],
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/6/68/Milmaru_Observatory_Tower.jpg',
    description: '세종시 전경을 내려다볼 수 있는 낮은 구릉 위의 생태공원. 평탄하게 정비된 흙길 산책로가 소형·중형견과 걷기에 딱 좋습니다.',
    why_recommended: '세종 신도시 전경을 한눈에 조망할 수 있는 구릉 위 생태공원입니다. 방문객이 적어 강아지와 조용히 산책하기에 좋으며, 전망대까지 완만한 오르막(약 300 m)은 소형견도 충분히 오를 수 있습니다.',
    tips: [
      '전망대까지 완만한 오르막 약 300 m — 소형견도 가능',
      '이른 아침 안개 낀 날 세종 전경이 특히 아름다움',
      '주차 공간 협소 (10여 대) — 평일 방문 권장',
      '자연 오솔길이라 진드기 예방 처리 필수',
    ],
    amenity_detail: {
      parking: '소규모 주차 공간 약 10대 (평일 권장)',
      trail:   '흙길 오솔길, 전망대까지 완만한 경사',
      shade:   '숲길로 그늘 있음',
      bench:   '전망대 주변 쉼터 벤치 몇 개',
    },
  },
  {
    id: '14',
    name: '방축천 생태공원',
    address: '세종특별자치시 아름동 일원',
    lat: 36.4998, lng: 127.2748,
    city: 'sejong',
    spot_type: 'riverside',
    size_suitable: ['small', 'medium', 'large'],
    features: ['trail', 'bench', 'water', 'shade'],
    image_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&q=80',
    description: '세종 신도시를 가로지르는 방축천 양안의 생태 하천공원. 평탄한 수변 산책로가 잘 정비돼 있어 소형견부터 대형견까지 편하게 걸을 수 있습니다.',
    why_recommended: '세종 신도시 도심 속을 흐르는 방축천 수변 공원입니다. 음악분수·야경·포장 산책로 등 도심 인프라가 잘 갖춰져 있어 저녁 산책으로도 훌륭하며, 반려견 유모차도 이동 가능한 포장 산책로가 약 6 km 이어집니다.',
    tips: [
      '음악분수 운영(주말 저녁) 시 방문객 급증 — 이른 아침 추천',
      '포장 산책로라 반려견 유모차·소형견 이동 편리',
      '중간 쉼터 인근 편의점 있어 간식·물 보급 가능',
      '하천 양안 합계 약 6 km — 코스 길이 조절 가능',
    ],
    amenity_detail: {
      trail: '포장 수변 산책로 약 6 km (양안 합계)',
      bench: '구간별 쉼터 벤치 다수',
      water: '음수대 여러 곳',
      shade: '교목 그늘 구간 있음 (전체의 약 40 %)',
    },
  },
  {
    id: '15',
    name: '세종 호수공원',
    address: '세종특별자치시 어진동 620',
    lat: 36.5049, lng: 127.2602,
    city: 'sejong',
    spot_type: 'park',
    size_suitable: ['small', 'medium', 'large'],
    features: ['parking', 'toilet', 'bench', 'trail', 'water', 'shade'],
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Sejong_lake_park_190609_01.jpg',
    description: '세종 정부청사 옆 호수를 중심으로 조성된 도심 공원. 넓은 잔디광장과 호수 둘레 평탄한 산책로가 모든 크기의 강아지와 여유롭게 걷기에 좋습니다.',
    why_recommended: '세종 정부청사 옆 호수를 중심으로 조성된 도심 공원으로, 호수 둘레 약 2.5 km 포장 산책로가 모든 견종에 적합합니다. 주변에 반려견 동반 가능한 카페가 여럿 있고, 잔디밭 배변봉투함이 비치되어 반려동물 친화 환경이 잘 갖춰져 있습니다.',
    tips: [
      '평일 오전이 가장 한적 — 사진 찍기에도 좋음',
      '주말 낮 방문객 많음, 이른 아침(7시 전) 추천',
      '호수 주변 반려견 동반 가능 카페 여러 곳',
      '잔디밭에 지정 배변봉투함 비치됨',
    ],
    amenity_detail: {
      parking: '공원 주변 공영 주차장 여러 곳 (유료)',
      toilet:  '공원 내 화장실 2개소',
      bench:   '호수 둘레 벤치 수십 개',
      trail:   '포장 호수 둘레 산책로 약 2.5 km',
      water:   '음수대 여러 곳',
      shade:   '교목·파고라 그늘 구간 다수',
    },
  },
];

@Injectable({ providedIn: 'root' })
export class SpotsService {
  getAll(): Spot[] {
    return SPOTS;
  }

  getById(id: string): Spot | undefined {
    return SPOTS.find(s => s.id === id);
  }

  getFiltered(city: City | null, size: DogSize | null): Spot[] {
    return SPOTS.filter(
      s => (!city || s.city === city) && (!size || s.size_suitable.includes(size)),
    );
  }
}
